# Generated by Django 4.2 on 2024-02-07 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="delivery_adress",
            new_name="delivery_address",
        ),
    ]
